server:
  port: 8082

spring:
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "order-1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

  datasource:
    name: ${POSTGRES_DB}
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

topic:
  send-methodData-event: send-methodData-event
  send-asyncMethodData-event: send-asyncMethodData-event